name: ser2net
version: '4.0'
summary: ser2net - Serial port to network proxy
description: |
  This daemon allows telnet and tcp sessions to be established with a
  host's serial ports. Combined with a terminal emulator, this can be a
  very simple means to configure network devices or other equipment with
  a serial port. This is remarkably similar to the reverse telnet
  feature of some Cisco routers.

  You will need to connect the raw-usb interface using:
      $ snap connect ser2net:raw-usb

  Example usage:
      $ ser2net.config-get > ser2net.yaml
        <edit the config>
      $ cat /tmp/ser2net.yaml |sudo /snap/bin/ser2net.config-set
      $snap restart ser2net.ser2net
confinement: strict
grade: stable
base: core

apps:
  ser2net:
    command: ser2net-wrapper
    daemon: simple
    restart-condition: on-failure
    plugs:
        - network-bind
        - raw-usb
        - serial-port
  config-get:
    command: config-get
  config-set:
    command: config-set

parts:
    gensio:
        plugin: autotools
        source: https://github.com/cminyard/gensio
        source-type: git
        build-packages:
            - python-dev
    ser2net:
        plugin: autotools
        source: https://github.com/cminyard/ser2net
        source-type: git
        source-tag: v4.0
        build-packages:
            - libyaml-dev
        override-build: |
            snapcraftctl build
            cp ser2net.yaml $SNAPCRAFT_PART_INSTALL
        after:
            - gensio
    glue:
        plugin: dump
        source: .
        organize:
            ser2net-wrapper: bin/ser2net-wrapper
            config-get: bin/config-get
            config-set: bin/config-set
        prime:
            - bin/*
